event_detector_operator_plugin:
  ros__parameters:

    use_sim_time: true
    startup_state: 3

    # buffer parameters
    buffer:
      default_time: 30.0
      default_queue_size: 20
      use_msg_stamp: true

    # analysis parameters
    analysis:
      default_period: 1.0

    # client names
    clients:
      - client0
      - client1
      - client2
      - client3
      - client4
      - client5
      - client6
      - client7
      - client8
      - client9
      - client10
      - client11
      - client12
      - client13
      - client14

    # client parameters by client name
    client_params:
      client0:
        tf_prefix: vehicles/vehicle_00
        client_data_list:
          - sensor_msgs__PointCloud2
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_00/pose
          sensor_msgs__PointCloud2:
            - topic: /vehicles/vehicle_00/lidar_center/pointcloud
      client1:
        tf_prefix: vehicles/vehicle_01
        client_data_list:
          - sensor_msgs__PointCloud2
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_01/pose
          sensor_msgs__PointCloud2:
            - topic: /vehicles/vehicle_01/lidar_center/pointcloud
      client2:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_02/pose
      client3:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_03/pose
      client4:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_04/pose
      client5:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_05/pose
      client6:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_06/pose
      client7:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_07/pose
      client8:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_08/pose
      client9:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_09/pose
      client10:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_10/pose
      client11:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_11/pose
      client12:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_12/pose
      client13:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_13/pose
      client14:
        client_data_list:
          - geometry_msgs__PoseStamped
        data:
          geometry_msgs__PoseStamped:
            - topic: /vehicles/vehicle_14/pose

    # rule names
    rules:
      - event_detector_operator_plugin::ProximityBasedDeploymentRule

    # analysis rule parameters by rule name
    rule_params:

      event_detector_operator_plugin::ProximityBasedDeploymentRule:
        enabled: true
        parameters:
          communication_type: "TYPE_MQTT"
          max_distance_to_start_deployment: 150.0
          min_distance_to_stop_deployment: 200.0
