apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-database
  labels:
    app: robotkube
    node: cloud-database
spec:
  replicas: 1
  selector:
    matchLabels:
      node: cloud-database
  template:
    metadata:
      labels:
        node: cloud-database
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mongodb
        image: mongo:6
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data/db
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: robotkube
spec:
  selector:
    node: cloud-database
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017