apiVersion: apps/v1
kind: Deployment
metadata:
  name: proximity-event-detector
  labels:
    app: robotkube
    node: proximity-event-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      node: proximity-event-detector
  template:
    metadata:
      labels:
        node: proximity-event-detector
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: robotkube-ed-k8s
          image: rwthika/robotkube-event-detector:2023-06
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              source install/setup.bash
              until ping -c 1 $ROS_HOSTNAME; do echo "Waiting for server ($ROS_HOSTNAME) ..."; sleep 0.1; done
              until rostopic list &> /dev/null; do echo "Waiting for rosmaster ($ROS_MASTER_URI) ..."; sleep 0.1; done
              roslaunch /docker-ros/ws/install/share/event_detector/launch/standalone_ed_k8s.launch
          env:
            - name: DOCKER_USER
              value: root
            - name: ROS_HOSTNAME # a container's own ROS_HOSTNAME that has to be equal this deployment's service name
              value: service-proximity-event-detector
            - name: ROS_MASTER_URI # must be equal to http://<master-deployment-service-name>:<master-deployment-service-port>
              value: http://service-robotkube-rosmaster-cloud:11311
          volumeMounts:
          - name: ed-params-k8s-rule-config-volume
            mountPath: /docker-ros/ws/install/share/event_detector/launch
            
      volumes:
      - name: ed-params-k8s-rule-config-volume
        configMap:
          name: ed-params-k8s-rule


---

apiVersion: v1
kind: Service
metadata:
  name: service-proximity-event-detector
  labels:
    app: robotkube
    node: proximity-event-detector
spec:
  clusterIP: None # Starts a headless service: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  ports: 
    - name: rosport-event-detector
      port: 11311
  selector:
    node: proximity-event-detector

    