apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosmaster-cloud
  labels:
    app: robotkube
    node: robotkube-ros-master-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      node: robotkube-ros-master-cloud
  template:
    metadata:
      labels:
        node: robotkube-ros-master-cloud
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: rosmaster-cloud-container
        image: ros:noetic-ros-core
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            source /opt/ros/$ROS_DISTRO/setup.bash
            roscore
        env:
          # no kubernetes logs are therefore visible with `kubectl logs`
          # You can either set DOCKER_USER=root or add `>> /proc/1/fd/1 2>> /proc/1/fd/2` behind the container command to solve this
          - name: DOCKER_USER
            value: root        
        ports:
        - containerPort: 11311
          name: rosmasterport

---

apiVersion: v1
kind: Service
metadata:
  name: service-robotkube-rosmaster-cloud
  labels:
    app: robotkube
    node: robotkube-ros-master-cloud
spec:
  clusterIP: None
  ports: 
    - port: 11311
  selector:
    node: robotkube-ros-master-cloud
