mqtt_client_target_vehicle_${ID}:
  ros__parameters:
    broker:
      host: service-mqtt-broker-mosquitto
      port: 1883
    bridge:
      mqtt2ros:
        mqtt_topics: 
          - mqtt/clients/vehicles/vehicle_${ID}/pose
        mqtt/clients/vehicles/vehicle_${ID}/pose:
          ros_topic: /clients/vehicles/vehicle_${ID}/pose
    client: 
        id: "mqtt_client_vehicle_${ID}_to_ed_k8s_target"