# This service Account is used for RBAC for the Application Manager
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-application-manager
  labels:
    tag: robotkube

---
# This service Account is used for RBAC for Configmap Watcher 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-configmap-watcher
  labels:
    tag: robotkube

---
# This service Account is used for RBAC for Kopf operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-kopf-operator
  labels:
    tag: robotkube
