apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-operator-pv
  labels:
    tag: robotkube
spec:
  storageClassName: standard
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /bookkeeping/mqtt
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-operator-pvc
  labels:
    tag: robotkube
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: mqtt-operator-pv
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard