apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-configmap-permission
  labels:
    app: robotkube
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["update", "create", "delete", "list"]  
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list"]