apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-client-vehicle-04-cloud
  labels:
    app: robotkube
    node: mqtt-client-vehicle-04-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      node: mqtt-client-vehicle-04-cloud
  template:
    metadata:
      labels:
        node: mqtt-client-vehicle-04-cloud
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mqtt-client-vehicle-04-cloud
        image: rwthika/robotkube-mqtt-client:2023-06
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            source install/setup.bash
            until ping -c 1 $ROS_HOSTNAME; do echo "Waiting for server ($ROS_HOSTNAME) ..."; sleep 0.1; done
            until rostopic list &> /dev/null; do echo "Waiting for rosmaster ($ROS_MASTER_URI) ..."; sleep 0.1; done
            roslaunch /docker-ros/ws/install/share/mqtt_client/params/standalone_mqtt_client.launch params_file:="/docker-ros/ws/install/share/mqtt_client/params/mqtt_params_vehicle_to_ed_k8s_target.yaml"
        env:
          - name: ROS_MASTER_URI # must be equal to http://<master-deployment-service-name>:<master-deployment-service-port>
            value: http://service-robotkube-rosmaster-cloud:11311
          - name: ROS_HOSTNAME # a container's own ROS_HOSTNAME that has to be equal this deployment's service name
            value: service-mqtt-client-vehicle-04-cloud
          - name: DOCKER_USER
            value: root
          - name: VEHICLE
            value: "vehicle_04"
        volumeMounts:
        - name: mqtt-vehicle-to-ed-k8s-target-config-volume
          mountPath: /docker-ros/ws/install/share/mqtt_client/params
      volumes:
          # the configmaps must be created (manually) before they can be used here
        - name: mqtt-vehicle-to-ed-k8s-target-config-volume
          configMap:
            name: mqtt-params-vehicle-to-ed-k8s-target

---

apiVersion: v1
kind: Service
metadata:
  name: service-mqtt-client-vehicle-04-cloud
  labels:
    app: robotkube
    node: mqtt-client-vehicle-04-cloud
spec:
  clusterIP: None # Starts a headless service: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  ports: 
    - name: rosport-cloud
      port: 11311
  selector:
    node: mqtt-client-vehicle-04-cloud
