event_detector:
  ros__parameters:

    # use_sim_time: true

    buffer:
      default_time: 30.0
      default_queue_size: 20
      use_msg_stamp: true

    clients:
      - client0
      - client1
      - client2
      - client3
      - client4
      - client5
      - client6
      - client7
      - client8
      - client9
      - client10
      - client11
      - client12
      - client13
      - client14

    client_params:
      client0:
        tf_prefix: vehicles/vehicle_00    # client-specific prefix of frames found in dynamic transforms
        client_data_list:
          - pointcloud
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_00/pose
          pointcloud:
            - topic: /clients/vehicles/vehicle_00/lidar_center/pointcloud
      client1:
        tf_prefix: vehicles/vehicle_01    # client-specific prefix of frames found in dynamic transforms
        client_data_list:
          - pointcloud
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_01/pose
          pointcloud:
            - topic: /clients/vehicles/vehicle_01/lidar_center/pointcloud
      client2:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_02/pose
      client3:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_03/pose
      client4:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_04/pose
      client5:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_05/pose
      client6:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_06/pose
      client7:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_07/pose
      client8:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_08/pose
      client9:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_09/pose
      client10:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_10/pose
      client11:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_11/pose
      client12:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_12/pose
      client13:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_13/pose
      client14:
        client_data_list:
          - pose
        data:
          pose:
            - topic: /clients/vehicles/vehicle_14/pose



    analysis:
      default_period: 1.0


    rules:

      event_detector_operator_plugin::ProximityBasedDeploymentRule:
        enabled: true
        parameters:
          max_distance_to_start_deployment: 150.0
          min_distance_to_stop_deployment: 200.0
