apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-${ID}-mqtt
  labels:
    tag: robotkube
    app: vehicle-${ID}-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-${ID}-mqtt
  template:
    metadata:
      labels:
        app: vehicle-${ID}-mqtt
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        node_id: vehicle${ID}
      containers:
      - name: mqtt-client-vehicle-${ID}
        image: k3d-robotkube-registry.localhost:41670/mqtt_client:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            source install/setup.bash
            ros2 launch mqtt_client standalone.launch.ros2.xml node_name:=mqtt_client_vehicle_${ID}_ego_data params_file:=/mounted_config/mqtt_params_vehicle_${ID}.yml
        volumeMounts:
        - name: mqtt-vehicle-${ID}-config-volume
          mountPath: /mounted_config
      volumes:
        - name: mqtt-vehicle-${ID}-config-volume
          configMap:
            name: mqtt-params-vehicles
