apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopf-operator-object-detection
  labels:
    tag: robotkube
    app: kopf-operator-object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kopf-operator-object-detection
  template:
    metadata:
      labels:
        app: kopf-operator-object-detection
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        node_id: cloud
      serviceAccountName: service-account-kopf-operator
      containers:
        - name: kopf-operator-object-detection
          image: k3d-robotkube-registry.localhost:41670/kopf_object_detection_operator:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - kopf run /operator/object_detection_operator.py
          volumeMounts:
          - name: kopf-operator-config-volume
            mountPath: /config
          - name: kopf-operator-bookkeeping
            mountPath: /bookkeeping_data
      volumes:
      - name: kopf-operator-config-volume
        configMap:
          name: kubernetes-operator-configuration
      - name: kopf-operator-bookkeeping
        persistentVolumeClaim:
          claimName: object-detection-operator-pvc
