mqtt_client_vehicle_13_pose:
  ros__parameters:
    broker:
      host: service-mqtt-broker-mosquitto
      port: 1883
    bridge:
      ros2mqtt:
        ros_topics: 
          - /vehicles/vehicle_13/pose
        /vehicles/vehicle_13/pose:
          mqtt_topic: mqtt/vehicles/vehicle_13/pose
    client: 
        id: "mqtt_client_vehicle_13_pose"