apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-mqtt-pose
  labels:
    tag: robotkube
    app: cloud-mqtt-pose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-mqtt-pose
  template:
    metadata:
      labels:
        app: cloud-mqtt-pose
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        node_id: cloud
      containers:
        - name: mqtt-client-cloud
          image: k3d-robotkube-registry.localhost:41673/mqtt_client:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              source install/setup.bash
              until ros2 topic list &> /dev/null; do echo "Waiting for ROS ..."; sleep 0.1; done
              ros2 launch /docker-ros/ws/install/share/mqtt_client/params/standalone_mqtt_client_cloud.launch.ros2.xml params_file:="/docker-ros/ws/install/share/mqtt_client/params/mqtt_params_cloud.yaml"
          volumeMounts:
          - name: mqtt-cloud-config-volume
            mountPath: /docker-ros/ws/install/share/mqtt_client/params
      volumes:
      - name: mqtt-cloud-config-volume
        configMap:
          name: mqtt-params-cloud
