apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosmaster-vehicle-10
  labels:
    app: robotkube
    node: robotkube-ros-master-vehicle-10
spec:
  replicas: 1
  selector:
    matchLabels:
      node: robotkube-ros-master-vehicle-10
  template:
    metadata:
      labels:
        node: robotkube-ros-master-vehicle-10
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: rosmaster-vehicle-container
        image: ros:noetic-ros-core
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            source /opt/ros/$ROS_DISTRO/setup.bash
            roscore
        env:
          - name: DOCKER_USER
            value: root        
        ports:
        - containerPort: 11311
          name: rosmasterport

---

apiVersion: v1
kind: Service
metadata:
  name: service-robotkube-rosmaster-vehicle-10
  labels:
    app: robotkube
    node: robotkube-ros-master-vehicle-10
spec:
  clusterIP: None
  ports: 
    - port: 11311
  selector:
    node: robotkube-ros-master-vehicle-10
