apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-03-mqtt
  labels:
    tag: robotkube
    app: vehicle-03-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-03-mqtt
  template:
    metadata:
      labels:
        app: vehicle-03-mqtt
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        node_id: vehicle03
      containers:
      - name: mqtt-client-vehicle-03
        image: k3d-robotkube-registry.localhost:41670/mqtt_client:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            source install/setup.bash
            ros2 launch mqtt_client standalone.launch.ros2.xml node_name:=mqtt_client_vehicle_03_ego_data params_file:=/mounted_config/mqtt_params_vehicle_03.yml
        volumeMounts:
        - name: mqtt-vehicle-03-config-volume
          mountPath: /mounted_config
      volumes:
        - name: mqtt-vehicle-03-config-volume
          configMap:
            name: mqtt-params-vehicles
