mqtt_client_vehicle_${ID}_pose:
  ros__parameters:
    broker:
      host: service-mqtt-broker-mosquitto
      port: 1883
    bridge:
      ros2mqtt:
        ros_topics: 
          - /vehicles/vehicle_${ID}/pose
        /vehicles/vehicle_${ID}/pose:
          mqtt_topic: mqtt/vehicles/vehicle_${ID}/pose
    client: 
        id: "mqtt_client_vehicle_${ID}_pose"